---
  - name: Tag - Update (Update Everything)
    ansible.builtin.import_tasks:
      file: tag_update.yml

  - name: Install Mosh
    ansible.builtin.apt: 
      name: mosh
      state: present

      